spring:
  main:
    web-application-type: reactive
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: products-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/product/**
        - id: orders-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/order/**
        - id: auth-service
          uri: http://localhost:4000
          predicates:
            - Path=/api/auth/**
    config:
      enabled: false
